spring:
  application:
    name: Zuul-Gateway
server:
  port: 12580

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8080/eureka/,http://peer2:8081/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      url: http://localhost:8082
    api-c:
      path: /api-c/**
      serviceId: Server-Consumer
    api-d:
      path: /api-d/**
      url: forward:/test
